containers/build

- README.md
The following Google doc captures the current design discussion for the proposed `acbuild` tool:
https://docs.google.com/document/d/1iEJt10J-Qhj7t6RocbmRLRvd90fGy0yYNFQsV1LWp7g/edit?usp=sharing
> *: acbuild design doc

- README.md
The command add-dep does not exist.
> README: fix command: "dependency add"

- CHANGELOG.md
Added changelog for acbuild's first release. The release will be tagged once this PR is accepted.
> release: added changelog for release v0.1.0

- README.md
Image signing and image fetching for begin were both still listed as
planned features, but they have been implemented.
Also added [cnt](https://github.com/blablacar/cnt) to the related works section.
> README: updated to reflect new features

- CHANGELOG.md
A couple of important bug fixes were merged in today, so I'd like to make a new minor release to include these.
> release: v0.1.1, a couple of critical bug fixes

- acbuild/acbuild.go
Fixes https://github.com/appc/acbuild/issues/67
The --modify flag creates a new temp directory, and then uses that as a
the build context for a call to begin, the given command, write, and
end. It was failing to use the alternate work context for the given
command.
The temp directory's path used by the --modify flag is also now based on
a sha512 hash of the absolute path of the given ACI to modify. This aims
to prevent concurrent invocations of --modify on the same ACI.
> *: --modify was broken, didn't call command with different work context

- acbuild/set-working-dir.go
- lib/set-working-dir.go
Fixes https://github.com/appc/acbuild/issues/78
> set-working-directory: added command to set the ACI's working directory

- lib/begin.go
- lib/common.go
- lib/end.go
- lib/write.go
- registry/fetch.go
- util/files.go
Didn't save a significant amount of code or logic.
> util: removed Exists function

- tests/annotation_test.go
- tests/begin_test.go
- tests/cat-manifest_test.go
- tests/common.go
- tests/dependency_test.go
- tests/end_test.go
- tests/environment_test.go
- tests/label_test.go
- tests/mount_test.go
- tests/port_test.go
- tests/replace-manifest_test.go
- tests/set-event-handler_test.go
- tests/set-exec_test.go
- tests/set-name_test.go
- tests/set-user_test.go
- tests/set-working-directory_test.go
More work towards https://github.com/appc/acbuild/issues/24.
> tests: added tests for cat-man, replace-man, set-eh, and set-wd

- lib/run.go
To prevent systemd from printing:
/etc/localtime does not point into /usr/share/zoneinfo/, not updating
container timezone.
The file pointed to by the /etc/localtime is copied into the expanded
ACI before execing systemd-nspawn.
Fixes https://github.com/appc/acbuild/issues/111 on any non-nixos system.
> run: mirror host's /etc/localtime symlink target in rootfs

- README.md
Continuing from https://github.com/appc/acbuild/pull/100#discussion_r45013507.
> README: rewrote the intro

- examples/acserver/build-acserver.sh
- examples/nginx/build-nginx.sh
Moved strings into functions, added arguments to acserver.
> examples: slightly tweaked acserver and nginx

- Documentation/getting-started.md
> docs: --insecure-skip-verify to --insecure-options

- acbuild/acbuild.go
When the modify flag was used, it was requiring that the initial
character for the path provided start with a `.` or a `/`. Since the
modify flag can only be used on local images, this was unnecessary.
Also when using the modify flag and the write failed (e.g. due to
permissions issues), the original image was deleted. This commit changes
it so that the write happens to a different file from the original, and
on success replaces the original with the new image.
> modify: don't require . or / for starting char, don't delete on failure

- lib/run.go
acbuild run will now check if the given binary exists, and will print a
nice error message if it doesn't, as opposed to relying on
systemd-nspawn to inform the user.
Additionally on systems where systemd's version is <228, systemd may
error out when attempting to exec a symlink. This adds a check for this
case, and prints a warning.
Fixes https://github.com/appc/acbuild/issues/165. Fixes https://github.com/appc/acbuild/issues/159.
New behavior when binary doesn't exist:
```
[nix-shell:~/go/src/github.com/appc/acbuild]$ sudo ./bin/acbuild run /bin/sh
/bin/sh: can't access tty; job control turned off
/ # 
[nix-shell:~/go/src/github.com/appc/acbuild]$ sudo ./bin/acbuild run /bin/shz
run: the binary "/bin/shz" doesn't exist
[nix-shell:~/go/src/github.com/appc/acbuild]$ sudo ./bin/acbuild run …
```
> run: check that the binary exists, error if not, warn if symlink

- lib/run.go
Reverts appc/acbuild#173
Wrong button :p
> Revert "run: add details to modprobe error"

- glide.lock
- glide.yaml
- registry/fetch.go
- vendor/github.com/appc/spec/discovery/discovery.go
- vendor/github.com/appc/spec/discovery/http.go
- vendor/github.com/appc/spec/schema/types/app.go
- vendor/github.com/appc/spec/schema/types/isolator.go
- vendor/github.com/appc/spec/schema/types/isolator_linux_specific.go
- vendor/github.com/appc/spec/schema/types/isolator_resources.go
- vendor/github.com/appc/spec/schema/version.go
- vendor/github.com/coreos/rkt/pkg/fileutil/fileutil.go
- vendor/github.com/coreos/rkt/pkg/multicall/multicall.go
Fixes https://github.com/appc/acbuild/issues/229
> vendor: appc v0.8.4 -> v0.8.5, rkt v1.7.0 -> v1.9.0

- registry/fetch.go
Fixes https://github.com/appc/acbuild/issues/235. Hopefully.
> registry: Fixed proxy use when insecure flag is set

- CHANGELOG.md
> release: v0.4.0

- Documentation/subcommands/set-supp-groups.md
- acbuild/set-supplementary-groups.go
- lib/set-supplementary-groups.go
Handles #265
One thing that I questioned adding is having a check for [NGROUPS_MAX ](https://www.j3e.de/ngroups.html), interested to hear thoughts.
Signed-off-by: grantseltzer <grantseltzer@gmail.com>
> Add command for setting supplementary GIDs

- lib/begin.go
> Fix Begin to return error generated when starting from local dir

- Documentation/subcommands/run.md
Fixes https://github.com/containers/build/issues/280
> docs: mention the --working-dir flag for the run subcommand

- Documentation/subcommands/write.md
- README.md
- acbuild/acbuild.go
- acbuild/write.go
- lib/write.go
Fixes https://github.com/containers/build/issues/252
For some definition of "fix"
> write: remove the --sign flag

- lib/copy.go
- util/files.go
This PR fixes two issues in OCI-mode `copy-to-dir` which were resulting in:
* copies to target paths missing directory prefix
* symlinks with empty target paths
> oci: fix copying and symlinking

- README.md
replaced youtube iframe with markdown
> Update youtube link markdown

- Documentation/subcommands/run.md
> Clarify interaction `resolv.conf` and engine

- lib/begin.go
> Warn when begin command isn’t run as superuser

- Documentation/dependencies.md
> Improve docs
