containers/build

- .gitignore
- README.md
- build
First thing folks typically want to know is how to build and install a
tool. So, we add a build script (ripped from appc/spec) and some
instructions to the README.md file.
> Add build/install instructions

- acbuild/abort.go
- acbuild/acbuild.go
- acbuild/annotation.go
- acbuild/begin.go
- acbuild/copy.go
- acbuild/dependency.go
- acbuild/end.go
- acbuild/environment.go
- acbuild/label.go
- acbuild/mount.go
- acbuild/port.go
- acbuild/run.go
- acbuild/set-exec.go
- acbuild/set-group.go
- acbuild/set-name.go
- acbuild/set-user.go
Each command now acquires a file lock on a file in the current working
context before performing any actions, and releases it upon completion.
This prevents concurrent invocations of acbuild from producing
unintended side effects.
> *: Implemented file locking for each command

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/fileutil/fileutil.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/fileutil/utimes_linux.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/fileutil/utimes_unsupported.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/fileutil/xattrs_linux.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/fileutil/xattrs_unsupported.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/multicall/multicall.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/sys/capability.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/sys/sys.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/sys/sys_linux.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/sys/sys_linux_386.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/sys/sys_linux_amd64.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/sys/sys_linux_arm.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/sys/sys_linux_arm64.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/tar/chroot.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/tar/tar.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/tar/tar_test.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/uid/uid.go
- Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go
- Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go
- Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_noop.go
- Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_test.go
- Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go
- Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go
- acbuild/acbuild.go
- util/files.go
The UnTar function failed to handle many edge cases in tar files (like
device nodes), so instead of implementing an untar function in acbuild,
a function from rkt is used.
> util: UnTar function rewritten to use github.com/coreos/rkt/pkg/tar

- lib/copy.go
- lib/end.go
For convenience, the copy command should create the parent directory for
the copy destination
> copy: create parent directory before attempting to copy

- README.md
- acbuild/acbuild.go
The `--modify=path/to/app.aci` flag has been added, and when provided acbuild will transparently wrap the call in `begin` and `end`, with the work context being set to a temp directory for the invocation.
As an example:
```
wget https://aci.gonyeo.com/nginx-latest-linux-amd64.aci
acbuild --modify=nginx-linux-latest-amd64.aci annotation add author "Derek Gonyeo"
```
(note this example won't work at the time of writing due to bug with acbuild's UnTar function)
> *: added context free mode

- README.md
- build-docker
This works well if your running a non-linux host and want to build `acbuild` in a VM that has Docker. It assumes that $PWD points to acbuild wherever your Docker host is running. In boot2docker/coreos-vagrant if you're sharing your homedir, this will be true.
> Add script to build acbuild in Docker

- lib/run.go
This change will check if the overlay fstype is already available before
attempting to load the module.
This can help acbuild run better from within a container itself, since often
the kernel modules won't be available to container, but the module will
potentially already be loaded.
@jonboulle @dgonyeo
> Check if overlay fstype is available before loading the module

- README.md
This updates the example commands in the README to work properly with the exec
command and name now being required before running "acbuild end".
@jonboulle @dgonyeo
> Update the README example commands.

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/appc/spec/aci/file_test.go
- Godeps/_workspace/src/github.com/appc/spec/discovery/discovery.go
- Godeps/_workspace/src/github.com/appc/spec/discovery/parse.go
- Godeps/_workspace/src/github.com/appc/spec/discovery/parse_test.go
- Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer/acirenderer_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/image_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/lastditch/common_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/lastditch/image_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/lastditch/labels.go
- Godeps/_workspace/src/github.com/appc/spec/schema/lastditch/pod.go
- Godeps/_workspace/src/github.com/appc/spec/schema/lastditch/pod_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/app.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/app_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/exec.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/exec_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_linux_specific.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_linux_specific_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_resources.go
- Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_resources_test.go
- Godeps/_workspace/src/github.com/appc/spec/schema/version.go
acbuild was using an older version of the appc/spec, which was causing
an issue with GetACI in registry/registry.go when the exec command of
a dependency wasn't set.
> godep: update appc/spec dependency

- lib/write.go
This changes the overwrite handling to adding the O_TRUNC flag onto the
OpenFile, rather than performing a remove and then recreate.
One primary use for this is running acbuild from a container, where the
ACI file is a bind mount in directly to the file. In this case, the
remove call won't work, but truncating the file is possible.
@jonboulle @dgonyeo
> write: Update to perform overwriting with truncate rather than remove

- tests/begin_test.go
- tests/common.go
Calls begin, and performs a handful of checks to verify that begin creates an empty container.
I want this to get merged before I write more tests, to confirm that I'm going about this the correct way.
The `ACBUILD_BIN` must be set and point to a binary of acbuild for the test to pass.
> tests: Added a test for begin

- acbuild/write.go
- lib/write.go
This changes the write operation to compress the resulting image with gzip.
Currently, it only does gzip. The ACI spec references gzip, bzip2, and xz.
Go has a built in gzip writer, but only a bzip2 reader. XZ is possible, however
it requires linking to libxz and then requiring it at runtime.
This changes also reorders some of the file closing within the write function.
It moves the closes from being done in line to being defered. The gzip.Writer
exposes a Close function, and want to ensure the Close options are done in
the proper order, and done across all three.
The ACI may be removed on a failure, however it is fine to remove the file
before closing, it will clean up properly.
> write: Instrumented gzip compression on the resulting image

- acbuild/acbuild.go
- acbuild/begin.go
- lib/begin.go
- registry/fetch.go
With this change if the ACI provided to begin does not exist on the
filesystem, meta discovery is performed to locate and download the ACI.
> begin: add support for fetching remote ACIs to start from

- acbuild/acbuild.go
- acbuild/version.go
- build
- lib/version.go
The version command was added. The version string gets set at compile
time by linker flags. If the build script is not used, the version will
read: "0.0.0+was-not-built-correctly".
Note that the build now fails when there are no git tags.
> version: added command

- tests/begin_test.go
- tests/common.go
Writes out an ACI, calls begin on it, and inspects it to make sure no
files were added to the rootfs and the manifest wasn't modified.
> tests: Added test for begin when starting with local ACI

- build
Was:
./bin/acbuild version
acbuild version "v0.1.0"
appc version 0.7.1+git
Is now:
./bin/acbuild version
acbuild version v0.1.0-dirty
appc version 0.7.1+git
> build: removed quotes from acbuild version string in build script

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/coreos/ioprogress/draw.go
- Godeps/_workspace/src/github.com/coreos/ioprogress/draw_test.go
- Godeps/_workspace/src/github.com/coreos/ioprogress/reader_test.go
- registry/fetch.go
The recent refactor resulted in the registry being correctly passed the
debug value, which exposed an issue with an additional progress bar that
was being drawn when uncompressing a dependency.
The panic was a combination of the logic drawing the bar passing the
ioprogress library a number that was too small for the total size, and
the ioprogress library not having a patch to be able to handle incorrect
numbers.
This commit removes the uncompressing bar, and updates the ioprogress
library.
Fixes https://github.com/appc/acbuild/issues/56
> run: --debug flag caused a panic with the Uncompress progress bar

- lib/begin.go
Sorry about this, but it looks like I typo'd a number when making a change for code review at some point. Don't know how I didn't catch this sooner.
> begin: fixed a silly typo that broke fetching remote ACIs

- examples/build-acserver.sh
- examples/build-nginx.sh
The nginx example requires https://github.com/appc/acbuild/pull/58 to function correctly.
> examples: Added example build scripts for acserver and nginx

- examples/build-nginx.sh
build-nginx.sh must be run as root. This adds a check for that.
> examples: added check if build-nginx.sh is running as root

- Vagrantfile
- scripts/vagrant-install-acbuild.sh
- scripts/vagrant-install-go.sh
Added a Vagrantfile and relevant scripts (largely stolen from rkt).
`vagrant up` should produce a machine with both acbuild and rkt 0.9.0
(will be updated once rkt is released) in the path.
> vagrant: added initial vagrant scripts

- util/files.go
When starting the build from an ACI, it was assumed it was an
uncompressed tar.
This commit uses NewCompressedReader from appc/spec/aci to handle ACIs
compressed with gzip, bzip2 and xz.
Fixes https://github.com/appc/acbuild/issues/36
> util: handle compressed ACIs

- lib/begin.go
- registry/fetch.go
- util/files.go
Noticed in #68. The latter is more accurate, particularly since this now
deals with compressed images. Also cleans up a few other variable names.
> *: rename UnTar -> ExtractImage

- README.md
SSH endpoint is for r/w access. Document using https so anyone can clone.
> readme: use github http endpoint

- acbuild/replace-manifest.go
- lib/replace-manifest.go
`replace-manifest` will overwrite the manifest in the current ACI with a given new ACI. Analogous to `actool`'s `patch-manifest --manifest=thing`
> replace-manifest: added command to replace manifest with a new one

- README.md
- lib/begin.go
- registry/fetch.go
When beginning a build with an empty ACI, use the runtime package to
populate the arch and os labels of the manifest.
> begin: populate the arch and os labels when starting with empty ACI

- acbuild/acbuild.go
- acbuild/annotation.go
- acbuild/dependency.go
- acbuild/environment.go
- acbuild/set-name.go
Simplified the code used in generating the help page. Template is
shorter, and has much fewer things passed into it. Combined all
add/remove command pairs.
New help output looks like this:
```
NAME:
acbuild - the application container build system
USAGE:
acbuild [command]
COMMANDS:
annotation [add|remove]         Manage annotations
begin                           Start a new build
copy                            Copy a file or directory into an ACI
dependency [add|remove]         Manage dependencies
end                             end a current build
environment [add|remove]        Manage environment variables
label [add|remove]              Manage labels
mount [add|remove]              Manage mount points
port [add|remove]               Manage ports
replace-manifest …
```
> help: refactored and rewrote code to generate help page

- acbuild/isolator.go
- lib/isolator.go
Fixes https://github.com/appc/acbuild/issues/42.
Example commands:
```
acbuild isolator add resource/cpu value.json
echo '{"request":"1G","limit":"2G"}' | acbuild isolator add resource/memory -
```
> isolators: added commands to add and remove isolators

- acbuild/acbuild.go
- acbuild/cat-manifest.go
- lib/cat-manifest.go
- util/manifest.go
This commit adds a command to cat the manifest, either from the current
build or from a given aci.
> cat-manifest: added implementation

- acbuild/set-event-handlers.go
- lib/set-event-handlers.go
Fixes https://github.com/appc/acbuild/issues/77.
> set-eh: added commands to set event handlers in the manifest

- lib/set-event-handlers.go
The type of function accepted by util.ModifyManifest changed with the
testing PR that got merged, and I forgot to git pull --rebase in the
set-event-handler PR before merging it.
> set-eh: fix compile error

- lib/run.go
- util/files.go
Modified the ExtractImage function in the util package to use the new
ExtractTarInsecure function when not running as root.
Also added a check to run for the current user to be root, so that a
nicer error message can be printed.
> util: extracting ACIs no longer requires root

- .travis.yml
- tests/common.go
Added a `.travis.yml` file to allow for travis CI to run.
Required a modification to `tests/common.go` to work in the travis environment.
> travis: added .travis.yml

- lib/begin.go
- lib/common.go
- lib/env.go
- lib/isolator.go
- lib/mounts.go
- lib/port.go
- lib/set-event-handlers.go
- lib/set-exec.go
- lib/set-group.go
- lib/set-user.go
- lib/set-working-dir.go
- tests/annotation_test.go
- tests/common.go
- tests/dependency_test.go
- tests/environment_test.go
- tests/label_test.go
- tests/mount_test.go
- tests/port_test.go
- tests/set-name_test.go
When presented with a manifest that lacked an App, many places in the
lib package would fill it in with a `&types.App{}`. This is incorrect, as
the user and group fields must be set in the struct for the manifest to
be valid. Without this fix, acbuild will error when asked to modify an
existing ACI in such a way that requires creating an App in the
manifest.
> *: many places were generating an invalid App struct

- lib/run.go
When run was searching the path for a given binary, it would attempt to
follow the symlink. This is incorrect, as the symlink might not be valid
until after the chroot. This commit fixes that.
> run: stop following symlinks when searching for binary in path

- Documentation/bash-scripts.md
- Documentation/context-free-mode.md
- Documentation/getting-started.md
- Documentation/subcommands/annotation.md
- Documentation/subcommands/begin.md
- Documentation/subcommands/copy.md
- Documentation/subcommands/dependency.md
- Documentation/subcommands/end.md
- Documentation/subcommands/environment.md
- Documentation/subcommands/label.md
- Documentation/subcommands/mount.md
- Documentation/subcommands/port.md
- Documentation/subcommands/run.md
- Documentation/subcommands/set-exec.md
- Documentation/subcommands/set-group.md
- Documentation/subcommands/set-name.md
- Documentation/subcommands/set-user.md
- Documentation/subcommands/write.md
- README.md
- lib/write.go
README was tweaked and greatly shortened. Documentation directory was
added, which includes a getting started guide, a description of context
free mode, and a suggested template for acbuild scripts. Each subcommand
got its own markdown file detailing its features and quirks.
Fixes https://github.com/appc/acbuild/issues/97 https://github.com/appc/acbuild/issues/99
> docs: refactored README into Documentation directory

- Documentation/subcommands/run.md
> Docs: fix misspelled systemd in run.md

- Documentation/subcommands/begin.md
- lib/begin.go
So as to provide better error messages when a user attempts to start a
build from a local file and this file doesn't exist, the user must
provide a path to the file starting with `/` or `.`.
Additionally, begin now properly cleans up whatever context it started
to make if an error is returned.
> begin: require first char to be / or . when starting from local file

- CHANGELOG.md
- Automatically fills in the `os` and `arch` labels on new builds.
- The `--modify` flag failed to properly use an alternate work context.
- The help page has been reformatted.
- Extracting ACIs during begin no longer requires root.
- Modifying an existing ACI that didn't have the `app` field set would cause an
error.
- Copy now has two modes of operation, toggled with the `-T` flag. The new mode
allows copying many files at once into the ACI, as opposed to a single one.
- When using begin with a local file, the path must now start with a `.`, `~`,
or `/`.
The following commands have been added to acbuild since the last release:
- cat-manifest
- isolator add
- isolator remove
- replace-manifest
- set-event-handler pre-start
- set-event-handler post-stop
- set-working-directory
> release: v0.2.0

- acbuild/copy.go
- tests/copy_test.go
To make the semantics a little less confusing, I restored the original
default behavior of copy to be the default, and put the new behavior
introduced recently behind the `--to-dir` flag.
```
acbuild copy nginx.conf /etc/nginx/nginx.conf
acbuild copy --to-dir foo bar/* foo/bar /tmp/baz
```
> copy: made -T the default behavior, put old default behind --to-dir

- CHANGELOG.md
v0.2.0 changed the default behavior of the copy command, requiring that the
user passed the `-T` flag to use the previous default behavior. This release
flips that, such that the default will be as it was before, and a new flag must
be passed to use the new behavior.
> release: v0.2.1

- Documentation/subcommands/copy.md
Forgot to update the documentation when I switched from the `-T` flag to the `--to-dir` flag.
> docs: update copy to reflect flipped semantics

- lib/run.go
This is necessary to allow for multiple run commands (for separate
builds) to be executing at the same time.
Fixes https://github.com/appc/acbuild/issues/131.
> run: don't register run commands with machined

- Documentation/subcommands/begin.md
- lib/begin.go
- tests/begin_test.go
To allow for users to specify an entire rootfs for their ACI, support
has been added to the begin command to allow for starting from a given
directory. This results in a non-empty rootfs, and an empty manifest.
Fixes https://github.com/appc/acbuild/issues/130, but with a different workflow than @ericchiang was expecting.
> begin: when given a directory, use as initial rootfs

- acbuild/port.go
The arguments for `acbuild port add` are `NAME`, `PROTOCOL`, and `PORT`,
but the example provided the latter two in the wrong order.
> port: fix swapped protocol and port in add usage example

- lib/run.go
The -q/--quiet flag was added to systemd-nspawn in version 209, and some
distros (like CentOS 7) ship with an older version than that. This
commit runs and parses `systemctl --version` to determine the version
number of systemd, and will only pass the --quiet flag if it's high
enough.
Fixes https://github.com/appc/acbuild/issues/140
> run: don't pass -q flag to systemd-nspawn for systemd < 209

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/coreos/rkt/LICENSE
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/tar/tar.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/uid/uid.go
The tar package didn't correctly handle hard links when the
ExtractTarInsecure package was called directly. This was recently fixed
in rkt, so this commit it to bump the version of rkt that acbuild uses.
Fixes https://github.com/appc/acbuild/issues/139 (for real this time).
cc @ecnahc515
> rkt: bumped vendored version to latest, pulls in fix for tar package

- lib/run.go
Fixes #145.  Also affects #142: `usr` is no longer a child of `rootfs` and `manifest` in `.acbuild/currentaci`.
> Fully resolves the path to /etc/localtime on the host.

- Documentation/subcommands/dependency.md
- acbuild/dependency.go
- lib/dependencies.go
Adds : syntax for specifying dependency versions. The two lines now do
the same thing:
```
acbuild dep add example.com/debian:jessie
acbuild dep add example.com/debian --label version=jessie
```
Partially fixes https://github.com/appc/acbuild/issues/128.
> dependency: added shorthand for specifying version tag

- Documentation/command-history.md
- acbuild/acbuild.go
- tests/annotation_test.go
- tests/common.go
- tests/copy_test.go
- tests/dependency_test.go
- tests/environment_test.go
- tests/label_test.go
- tests/mount_test.go
- tests/port_test.go
- tests/replace-manifest_test.go
- tests/set-event-handler_test.go
- tests/set-exec_test.go
- tests/set-group_test.go
- tests/set-name_test.go
- tests/set-user_test.go
- tests/set-working-directory_test.go
This commit has acbuild maintain annotations following
"acbuild-command-%d". Each new acbuild command that isn't something like
cat-manifest or write results in a new annotation being added to the
image, containing the command that was run.
Fixes https://github.com/appc/acbuild/issues/120.
> *: add annotations to track acbuild commands

- CHANGELOG.md
appc spec version: v0.7.1+git
v0.2.2 is a minor release incorporating a handful of changes since v0.2.1. Things this release includes:
- Don't require a starting character of `.` or `/` when specifying an image for
the `--modify` flag.
- Adds support for specifying a local directory with `begin`, for use as the
initial rootfs of the ACI.
- Adds support for the `run` command on systems with a version of systemd <
209.
- Versions of dependencies can be specified using tag syntax.
- A bug related to the handling of hard links in tars was found, and fixed.
- A history of acbuild commands performed is now tracked in annotations in the
ACI being worked on. This can be disabled via a flag.
> release: v0.2.2

- lib/run.go
Depending on the image, the PATH variable inside of a acbuild run
command could be propagated from something on the host. On normal
distros, this was mostly a non-issue. On NixOS, it would get set to
"/no-such-path:/sbin:/bin", which is definitely an issue.
This commit checks if the PATH environment variable has been set in the
ACI's manifest (which gets added to the systemd-nspawn command), and if
it has not it sets it to
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin".
Note that it only sets it on the systemd-nspawn command, it doesn't
add or modify the PATH variable in the manifest.
> run: set the PATH variable if not set by manifest

- acbuild/set-name.go
The example gives `acbuild name quay.io/foo/bar` which doesn't work.
> Fix set-name example text.

- Documentation/subcommands/run.md
Press Ctrl+] three times.
Fixes https://github.com/appc/acbuild/issues/169.
> docs: explains how to break out of an acbuild run command

- lib/run.go
If overlayfs isn't available on a user's system, acbuild attempts to modprobe it. If this fails, acbuild would exit with `run: exit status 1`. This is a very confusing error message to receive, so this commit checks for this failure and instead prints `run: overlayfs is not supported on your system`.
Fixes https://github.com/appc/acbuild/issues/164
> run: show a friendlier error message when unable to modprobe overlayfs

- acbuild/acbuild.go
If the user calls acbuild with invalid subcommands or flags, and the
code for no subcommand is called, acbuild would up until now exit with
exit code 0. This can break scripts relying on the exit code to catch
errors.
This commit changes this such that acbuild will exit with code 3 when
called with invalid subcommands or flags.
Fixes https://github.com/appc/acbuild/issues/160.
> *: exit with error code 3 when arguments are invalid

- lib/end.go
- lib/run.go
- util/mounts.go
If acbuild was killed in the middle of an `acbuild run` command, the
overlayfs it mounts at .acbuild/target would remain mounted. This caused
issues whenever the user attempts to use `acbuild end` to clean up after
the failed build.
Fixes https://github.com/appc/acbuild/issues/168.
> run/end: check if .acbuild/target is mounted, unmount if so

- scripts/vagrant-install-acbuild.sh
Currently the Vagrant install script uses Rkt 0.9.0. Version 1.1.0 was released recently, so update to that.
This was previously submitted as #183, but I renamed the branch, which confused GitHub...
Test Plan:
```sh
git clone https://github.com/coreos/coreos-baremetal.git
cd coreos-baremetal/contrib/dnsmasq
./get-tftp-files
sudo ./build-aci
```
> Update Vagrant script to use Rkt 1.1.0

- registry/fetch.go
The `bar` function subtracts 2 from the barSize; if barSize is < 2, drawing the progress bar will panic because you can't `string.Repeat` a negative length.
```
Running: [/src/config.sh]
meta tag not found on XX.XXXXXXXXX.XXX/XXX-XXX/XXXX/XXXXXXX-XXXX-XXXXXXX: expected a 200 OK got 403
panic: runtime error: makeslice: len out of range
goroutine 1 [running]:
strings.Repeat(0x857ee0, 0x1, 0xfffffffffffffffe, 0x0, 0x0)
/usr/lib/golang/src/strings/strings.go:458 +0x68
github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress.func·004(0x0, 0x37ae506, 0x0, 0x0)
/root/acbuild/gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress/draw.go:112 +0x270
github.com/appc/acbuild/registry.func·002(0x0, 0x37ae506, 0x0, 0x0) …
```
> Fix panic when the prefix is > 61 chars

- acbuild/run.go
- lib/run.go
The current directory for the command executed by `acbuild run` can now
be set with the flag `--working-dir`. This requires systemd >= 229.
Fixes https://github.com/appc/acbuild/issues/154.
> run: added flag --working-dir=/path

- Documentation/subcommands/begin.md
- lib/begin.go
This commit modifies begin such that after a local file has been given
to acbuild and it's been extracted, acbuild will check for the existence
of a manifest and a rootfs. If either is missing, it's assumed that the
tarball acbuild just extracted is the rootfs for the container, and it
will move the files into the rootfs directory and create an empty
manifest.
Fixes https://github.com/appc/acbuild/issues/156
> begin: when provided file doesn't look like an ACI, it's a rootfs tar

- Documentation/subcommands/copy-to-dir.md
- Documentation/subcommands/copy.md
- acbuild/copy-to-dir.go
- tests/copy_test.go
Copy's semantics are weird and I don't like them, but there are
technical reasons preventing `acbuild copy` from being reasonable. This
commit breaks the --to-dir flag on `acbuild copy` out into a separate
command, so that when users notice that `acbuild copy` doesn't do what
they expect it'll be a little more obvious that there are two modes of
operation here. Hiding this away in a flag, and therefore inside a help
page that wasn't at the top level, wasn't very user friendly.
Fixes https://github.com/appc/acbuild/issues/163.
> copy: split --to-dir flag into separate subcommand

- .travis.yml
- Documentation/subcommands/run.md
- README.md
- acbuild/run.go
- engine/common.go
- engine/systemdnspawn/systemdnspawn.go
- lib/run.go
- tests/begin_test.go
- tests/common.go
- tests/run_test.go
This commit revamps `lib/run.go` to rely on external binaries to perform
the actual execution of the desired command. Each external binary, or
engine, is expected to either exist on the PATH or in the same directory
as the acbuild binary, and must be named as `acbuild-$ENGINENAME`. The
default (and currently only) engine is systemd-nspawn.
When the engine is started a JSON message detailing what it is to run
and with what environment variables is written into it on stdin. The
package `github.com/appc/acbuild/engine` has been added to define the
schema for this (and also holds some helper utilities for engines).
Almost fixes https://github.com/appc/acbuild/issues/13.
Kind of a workaround for https://github.com/appc/acbuild/issues/162.
> run: add support for swappable engines

- scripts/vagrant-install-go.sh
After install ubuntu i could not install git with error "Package git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source"
> Add apt-get update to ubuntu

- Documentation/subcommands/isolator.md
A common question is how to retain linux capabilities in an ACI via
acbuild, which is done with the isolator command.
This commit adds docs on the command, which includes a simple example
for retaining a capability.
> docs: add basic docs for isolator, mention capabilities

- README.md
Without the `systemd-container` package installed on Ubuntu there are no systemd container/nspawn tools.
> Mention the need for `systemd-container` on Ubuntu

- Vagrantfile
The vivid64 image is no longer available.
Fixes https://github.com/appc/acbuild/issues/187.
> vagrant: use xenial64 instead of vivid64

- README.md
Go 1.5+ is needed to build from source, updates readme to reflect that.
> readme: requires Go to build from source

- Documentation/subcommands/run.md
- Documentation/subcommands/set-exec.md
- acbuild/run.go
- acbuild/set-exec.go
The -- flag influences how acbuild determines which flags are intended
for itself and which flags to pass along, but this was missing from the
examples and documentation.
Fixes https://github.com/appc/acbuild/issues/213.
> docs: articulate the necessity of `--` in run and set-exec

- engine/systemdnspawn/systemdnspawn.go
This commit attaches stdin to the process executed during run commands,
which allows the user to pipe data into this process.
```
derek@proton ~/go/src/github.com/appc/acbuild> sudo ./bin/acbuild begin quay.io/coreos/alpine-sh           
Downloading quay.io/coreos/alpine-sh: [========================] 2.65 MB/2.65 MB
derek@proton ~/go/src/github.com/appc/acbuild> echo "this is a test" | sudo ./bin/acbuild run -- dd of=/test
0+1 records in
0+1 records out
derek@proton ~/go/src/github.com/appc/acbuild> sudo ./bin/acbuild run -- cat /test                          
this is a test
```
Fixes https://github.com/appc/acbuild/issues/200.
> engine: attach stdin to the process

- engine/systemdnspawn/systemdnspawn.go
Starting in systemd 230, systemd-nspawn requires the file
/etc/machine-id to be populated in the container for some reason. There
does not appear to be a flag to disable this, and the commit message I
found for the systemd commit that I think causes this is rather vague as
to why this is necessary.
To work around this, this commit copies /etc/machine-id in from the host
and removes it after the command has run.
Fixes https://github.com/appc/acbuild/issues/217.
> engine/systemdnspawn: copy in the host's /etc/machine-id for >= 230

- Documentation/subcommands/label.md
- lib/begin.go
The runtime.GOARCH value isn't accepted by the AppC spec as a value for
the arch label in a manifest when on an arm platform. This commit adds a
case to use "armv7l" whenever runtime.GOARCH is "arm". Additionally
(when on arm) this change scans all files at the build start and any
files copied in later for executables, and will switch the label between
"armv7l" and "armv7b" when it finds a little or big endian binary.
Fixes https://github.com/appc/acbuild/issues/190.
> begin/copy: scan for arm executables, update arch label when found

- scripts/vagrant-install-go.sh
Currently the which git check is irrelevant. This combines the two actions in the same logic. 
$ true || echo "false" && echo "not needed"
not needed
$ true || { echo "false" && echo "not needed"; }
$
> do not install git again if it exists

- lib/isolator.go
- tests/isolator_test.go
`acbuild isolator add ...` was broken, producing the error:
```
isolator add: json: error calling MarshalJSON for type *types.App: invalid isolator
```
This commit fixes this, and adds a test for isolator add to be able to
catch this type of regression in the future.
Fixes https://github.com/appc/acbuild/issues/238.
> isolator: fixed isolator, added test

- Documentation/subcommands/run.md
- acbuild/run.go
- build
- engine/chroot/chroot-child.go
- engine/chroot/chroot.go
- engine/common.go
- engine/systemdnspawn/systemdnspawn.go
Added a chroot run engine to acbuild. This will allow people who have
problems with systemd-nspawn and people who don't have systemd to use
acbuild run, by specifying `--engine=chroot` on any run commands.
> engine: added a chroot engine

- build
- scripts/vagrant-install-acbuild.sh
- scripts/vagrant-install-go.sh
Fixes a couple issues I ran into trying to build acbuild with Vagrant/VirtualBox on OS X.
* Hard links are not allowed on an OS X shared folder
Fixes issue with building acbuild on Vagrant on OS X:
```
==> default: ln: failed to create hard link '/vagrant/bin/acbuild-script'
=> '/vagrant/bin/acbuild'
==> default: : Operation not permitted
```
* vagrant build uses go 1.5 (matches build-docker)
* Only attempt to add the group `rkt` if it doesn't currently exist (`vagrant provision` succeeds after initial provision)
> Vagrant on OS X tweaks

- Documentation/dependencies.md
Added more information on dependencies to the docs, since this is a common source of questions from new users. (e.g. https://github.com/containers/build/issues/260)
> docs: added docs detailing how dependencies work

- README.md
The instructions don't work as-is.  It's a simple matter, presumably the repo was formerly called "acbuild".  I think it makes more sense to clone it into a dir called `acbuild` than to update the rest of the instructions.
> Update clone destination

- README.md
Oops, looks like I missed the second `clone` command.  See 27cedb24a22fbe7354c2d0cdd281f0bfe80a665f for related change.
> Fix clone destination

- Documentation/dependencies.md
In " Specifics on using it are here," 'here' gets rendered as a link to https://github.com/containers/build/blob/master/Documentation/Documentation/subcommands/dependency.md
> Fix relative links to docs

- Vagrantfile
As originally noted in
https://github.com/appc/acbuild/issues/234#issuecomment-238365738, it appears
the script `scripts/vagrant-install-go.sh` intends to be executed via the
synced folder functionality of Virtualbox, which requires the Virtualbox Guest
Additions to be installed in the guest VM. As noted, this is missing from the
Xenial image (see bug https://bugs.launchpad.net/cloud-images/+bug/1565985).
This implements a workaround for this bug, and is a first step towards fixing
the Vagrant-based option for building `acbuild` (see
https://github.com/appc/acbuild/issues/234#issuecomment-238393500 for why this
is just the first step).
Fixes #234.
> Workaround: install missing Virtualbox Guest Additions in Xenial

- acbuild/script.go
Fixes https://github.com/containers/build/issues/288
> script: error if end is detected in a script

- lib/run.go
- registry/fetch.go
If fetching a dependency for a run command, and the registry returns a
404 error, intercept that and print a more user-friendly error saying
that the dependency doesn't exist.
Example:
```
derek@proton 1 ~/go/src/github.com/containers/build> sudo ./bin/acbuild run -- apk update
run: dependency "quay.io/coreos/alpine-sh:doesnt-exist" doesn't appear to exist: bad HTTP status code: 404
```
Fixes https://github.com/containers/build/issues/283
> lib/run: better error output when dependency doesn't exist

- lib/common.go
- lib/end.go
When a subcommand attempts to grab a lock due to permission denied or
end fails to delete something due to permission denied, a warning will
now be printed advising the user to run the command as root.
Example:
```
derek@proton ~/go/src/github.com/containers/build> ./bin/acbuild end
you'll need to run this as a user with appropriate privileges
end: remove .acbuild/currentaci/rootfs/var/www/localhost/htdocs: permission denied
```
Fixes https://github.com/containers/build/issues/284
> lib/end: print a warning to run as root when permission denied

- engine/chroot/chroot.go
`/etc/resolv.conf` can be a symlink (eg. Fedora 25), but the symlink likely won't resolve inside the chroot. Copy `/etc/resolv.conf` as regular file instead.
Previous behaviour:
```
$ sudo "PATH=$(pwd)/bin:$PATH" bin/acbuild begin --debug ./library-alpine-3.5.aci
Beginning build with ./library-alpine-3.5.aci
$ sudo "PATH=$(pwd)/bin:$PATH" bin/acbuild run --engine chroot -- \
sh -c 'ls -la /etc/resolv.conf && cat /etc/resolv.conf'
lrwxrwxrwx    1 root     root            35 Mar  7 22:22 /etc/resolv.conf -> /var/run/NetworkManager/resolv.conf
cat: can't open '/etc/resolv.conf': No such file or directory
```
New behaviour:
```
$ sudo "PATH=$(pwd)/bin:$PATH" bin/acbuild run --engine chroot -- \
sh -c 'ls -la /etc/resolv.conf && cat /etc/resolv.conf'
-rw-r--r--    1 root     root           123 …
```
> Handle host /etc/resolv.conf being a symlink

- lib/oci/manifest.go
This PR fixes a bug where the mediaType for layers was incorrectly set to "MediaTypeImageLayer" literal.
> oci/manifest: use actual ImageLayer media type

- lib/common.go
This fixes blob-layer digests in OCI images, by performing digest
computation on the final gzip'd layers content as specified by
current image-spec.
> oci: fix blob-layer digest computation

- acbuild/acbuild.go
- acbuild/write.go
- lib/write.go
solves #305
It currently doesn't implement an option to turn id generation on or off, but the hash is computed concurrently to the disk wirtes, so I do not think there will be an performance impact.
> write: print image id on successfull write;

- lib/common.go
- lib/copy.go
- lib/oci/manifest.go
- lib/run.go
Disable gzip compression for OCI image layers in order to get Docker to run it properly. If gzip compression is turned on, Docker complains about a layer checksum mismatch because it calculates the checksum after
decompressing it.
Here's how to reproduce it:
1. Build an OCI image (containing a trivial hello world application) and push it to Docker Hub using [skopeo](https://github.com/projectatomic/skopeo):
```
$ ./acbuild begin --build-mode=oci
$ ./acbuild copy hello /hello
$ ./acbuild set-exec /hello
$ ./acbuild write myimage.oci
$ mkdir myimage
$ tar xf myimage.oci -C myimage
$ ./skopeo copy oci:myimage docker://mwuertinger/oci-test
```
2. Trying to pull the image with Docker yields an error:
```
$ docker pull mwuertinger/oci-test
Using default tag: latest
latest: Pulling from …
```
> Store DiffIDs correctly in OCI config

- examples/nodejs/build-nodejs.sh
The variables are now expanded when the script is interpreted, rather than when the script is invoked. This causes the wrong status code to be propagated. This patch fixes that. Thanks!
> fix node-build trap script

- lib/common.go
The err value was accidentally getting overriden with the error from the
os.Stat call.
> lib: show correct error when loadManifest fails

- acbuild/copy.go
Resolves #201. See https://github.com/containers/build/issues/201#issuecomment-215243446.
> Error on trailing path separator in copy command
